### ISSUE TITLE
Feature Request - Support for syncing actions from private repos

### ISSUE THREAD

**Issue by harshtrivedi134** [actions/actions-sync#74]
I believe actions-sync can only download actions from public repos in github.com. What was the reason to only include public repos and not private repos? It would be great to hear if you are considering private repos in your roadmap.

**Comment by FLuzzi-csw** [comment]
I'm also having this problem!
Pretty sure that adding a `--source-token` flag would resolve this problem

**Comment by FLuzzi-csw** [comment]
Hi, unfortunately this doesn't solve the problem, `actions-sync` errors out requesting authentication
```

**Comment by shawnHartsell** [comment]
> Hi, unfortunately this doesn't solve the problem, `actions-sync` errors out requesting authentication
> 
> ```
> pulling $REPO to $CACHE/$REPO ...
> could not pull $REPO, the repository may require authentication or does not exist
> ```

😕, I tested again on `main` and can pull both personal private repos, as well as internal and private org owned repos. Silly question; are you replacing the `$` in my example with actual values (the error message looks like you forgo, unless you're redacting them 😄)? In addition, you'll also need to make sure of the following:

- when setting the repo, include the owner name (e.g. `my-org/my-repo`)
- when pulling org owned repos make sure to [enable SSO](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on) on the token

**Comment by FLuzzi-csw** [comment]
Hi i'll try to give you some more context:
i'm using a self-hosted runner to syncronize some private actions, the specific call that I've tried to make is
```
actions-sync sync --cache-dir . --destination-token "${{ secrets.GHE_TOKEN }}" --destination-url "${{ secrets.GHE_HOST}}" --source-url "https://${{ secrets.GH_USER }}:${{ secrets.GH_PAT }}@github.com" --repo-name-list-file ./repo_name_list.txt
```
This command will fail with the error code that you referenced.

Does [go-git](https://github.com/go-git/go-git) support this kind of url?
I haven't found any information about it.

---

Compiling and running the executable including the changes in this PR.
```
actions-sync sync --cache-dir . --destination-token "${{ secrets.GHE_TOKEN }}" --destination-url "${{ secrets.GHE_HOST}}" --source-token "${{ secrets.GH_PAT }}" --source-user "${{ secrets.GH_USER }}" --repo-name-list-file ./repo_name_list.txt
```
---
I also have to note that i don't have the option to [enable SSO](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on), I'm using standard `Token (classic)`

**Comment by FLuzzi-csw** [comment]
> Does [go-git](https://github.com/go-git/go-git) support this kind of url?

Looking at the code it seems like that this type of auth is not supported (correct me if i'm wrong).
To support it we'd need to parse the url to extract those informations, then pass them to [go-git](https://github.com/go-git/go-git) like I did in [this PR](https://github.com/actions/actions-sync/pull/114/files#diff-90b3eeb967ec278c5665f19af883dfdfb90936ea240e0028a31dfac63d74e0daL75-L78).

**Comment by shawnHartsell** [comment]
> Hi i'll try to give you some more context: i'm using a self-hosted runner to syncronize some private actions, the specific call that I've tried to make is
> 
> ```
> actions-sync sync --cache-dir . --destination-token "${{ secrets.GHE_TOKEN }}" --destination-url "${{ secrets.GHE_HOST}}" --source-url "https://${{ secrets.GH_USER }}:${{ secrets.GH_PAT }}@github.com" --repo-name-list-file ./repo_name_list.txt
> ```
> 
> ```
> # repo_name_list.txt
> ORG/action-1
> ORG/action-2
> ```
> 
> This command will fail with the error code that you referenced.

Odd, we're not observing the same behavior even when running the `sync` command. For example, we're able to sync a private repo to a GHES instance using an action that runs on a self-hosted runner (in this case `darwin/arm64`). The value of `secrets.ACTIONS_SYNC_SOURCE_URL` is of the form `https://<USERNAME>:<PAT_TOKEN>@github.com`

```yml
name: sync actions
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: download actions-sync
        run: |
          wget https://github.com/actions/actions-sync/releases/download/v202404051308/gh_202404051308_darwin_arm64.tar.gz
          tar -xf gh_202404051308_darwin_arm64.tar.gz
              
      - name: sync actions
        run: |
          mkdir -p cache
          ./bin/actions-sync sync \
          --cache-dir "cache" \
          --source-url "${{secrets.ACTIONS_SYNC_SOURCE_URL}}" \
          --destination-url "${{secrets.ACTIONS_SYNC_DEST_URL}}" \
          --destination-token "${{secrets.ACTIONS_DEST_TOKEN}}" \
          --repo-name-list "<OWNER>/<REPO>"

```


> Does [go-git](https://github.com/go-git/go-git) support this kind of url? I haven't found any information about it.
> 

It supports this type of url b/c under the hood the pkg uses [`net/url` types](https://github.com/search?q=repo%3Ago-git%2Fgo-git%20NewRequest&type=code) from the standard library which supports the [user info component in URIs](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1). 

Example:https://go.dev/play/p/gpbDmQ0ct14


That being said, I'm not opposed to the additional flags that's being proposed in #114 as it would make the API of the CLI more consistent and explicit. However, I'd like to see if we achieve more consistency such as not requiring a `--source-user`. For example, the `push` command only requires a token (b/c it creates its client differently).
